version: '3'

services:
  postgresql:
    image: postgres
    container_name: user
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DATABASE=user
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-user
    ports:
      - '6379-6379'
